# Generated by Django 4.0.4 on 2022-06-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0005_alter_products_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('outlet', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_brands', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_categories', to='products.categories')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_products', to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to='accounts.profile')),
            ],
            options={
                'verbose_name_plural': 'Offlie Sales',
            },
        ),
    ]
