# Generated by Django 3.2.6 on 2022-06-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfflineSale',
        ),
    ]
