# Generated by Django 3.2.6 on 2022-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_productreview_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Flash Sale Name')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='End Time')),
                ('products', models.ManyToManyField(to='products.Products')),
            ],
            options={
                'verbose_name_plural': 'Flash Deal',
            },
        ),
    ]
