# Generated by Django 3.2.6 on 2022-07-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview_is_approved'),
        ('flash_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(related_name='flash_products', to='products.Products'),
        ),
    ]
