# Generated by Django 3.2.6 on 2022-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sale', '0002_alter_flashsale_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Flash Discount'),
        ),
    ]
