# Generated by Django 3.2.6 on 2022-08-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sale', '0002_flashproducts_flash_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsale',
            name='discount',
        ),
    ]
