# Generated by Django 3.2.7 on 2022-07-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_billingaddress_options_billingaddress_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='is_biling',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='is_billing',
            field=models.BooleanField(default=False, verbose_name='Is Billing Address'),
        ),
    ]
