# Generated by Django 3.2.6 on 2022-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220528_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_ID',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Customer ID'),
        ),
    ]
