# Generated by Django 3.2.6 on 2022-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_points_gained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='area',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Area Name'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(max_length=300, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='post_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='region',
            field=models.CharField(max_length=300, null=True, verbose_name='Region Name'),
        ),
    ]
