# Generated by Django 4.0.4 on 2022-05-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permission',
            field=models.ManyToManyField(to='accounts.userpermission'),
        ),
    ]
