# Generated by Django 3.2.6 on 2022-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220607_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.ManyToManyField(to='accounts.UserPermission'),
        ),
    ]
