# Generated by Django 3.2.6 on 2022-08-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_banner_options_alter_bannerproduct_options_and_more'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuehistory',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products', verbose_name='Product Refer'),
        ),
    ]
