# Generated by Django 4.0.4 on 2022-06-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_remove_customerblog_user_delete_adminblog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Blog'},
        ),
    ]
