# Generated by Django 3.2.6 on 2022-05-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_products_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Supplier Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('ref_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch No')),
                ('date_of_purchase', models.DateField(blank=True, null=True, verbose_name='Date of Purchase')),
                ('order_status', models.CharField(choices=[('1', 'Recieved'), ('2', 'Pending'), ('3', 'Ordered')], max_length=100, null=True, verbose_name='Order Status')),
                ('outlet_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Outlet Name')),
                ('price', models.FloatField(null=True, verbose_name='Prce')),
                ('unit_cost', models.FloatField(blank=True, null=True, verbose_name='Net Unit Cost')),
                ('other_cost', models.FloatField(null=True, verbose_name='Other Cost')),
                ('due_price', models.FloatField(blank=True, null=True, verbose_name='Due Price')),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Method')),
                ('payment_status', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Partial'), ('3', 'Paid')], max_length=100, null=True, verbose_name='Payment Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products', verbose_name='Select product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='inventory.supplier', verbose_name='Select Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
