# Generated by Django 4.0.4 on 2022-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_status',
            field=models.CharField(choices=[('Received', 'Recieved'), ('Pending', 'Pending'), ('Ordered', 'Ordered')], max_length=100, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], max_length=100, null=True, verbose_name='Payment Status'),
        ),
    ]
