# Generated by Django 4.0.5 on 2022-07-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='batch_no',
        ),
    ]
