# Generated by Django 4.0.4 on 2022-05-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchase History'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Supplier List'},
        ),
    ]
