# Generated by Django 3.2.6 on 2022-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='batch_no',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Batch No'),
        ),
    ]
