# Generated by Django 4.0.5 on 2022-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchase_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('bank_name', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'BankAccounts',
            },
        ),
    ]
