# Generated by Django 4.0.5 on 2022-07-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_purchase_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch No'),
        ),
    ]
