# Generated by Django 3.2.6 on 2022-08-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchase_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='due_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Due Price'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='other_cost',
            field=models.FloatField(default=0, null=True, verbose_name='Other Cost'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Net Unit Cost'),
        ),
    ]
