# Generated by Django 4.0.5 on 2022-07-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_batch_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='batch_no',
        ),
    ]
