# Generated by Django 4.0.5 on 2022-07-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bankaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
