# Generated by Django 3.2.6 on 2022-07-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_quantity_products_attribute'),
        ('inventory', '0003_alter_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_product', to='products.products', verbose_name='Select product'),
        ),
    ]
