# Generated by Django 4.0.5 on 2022-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchase_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bin_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bin Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='manager_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Manager Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='manager_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Manager Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Owner Contact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='routhing_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Routing Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Swift Code'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='trade_licence_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trade Licence'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='warehouse_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Warehouse Number'),
        ),
    ]
