# Generated by Django 4.0.5 on 2022-07-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchase_product'),
        ('inventory', '0004_expenses_expence_amount'),
    ]

    operations = [
    ]
