# Generated by Django 4.0.5 on 2022-07-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_merge_20220724_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='outlet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_outlet_name', to='inventory.outlet'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_acc_name', to='inventory.bankaccounts'),
        ),
    ]
