# Generated by Django 4.0.5 on 2022-07-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_purchase_outlet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwithdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='depositwithdraw',
            name='date_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
