# Generated by Django 4.0.5 on 2022-07-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_depositwithdraw_amount_depositwithdraw_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
