from products.database.feature_product import Banner, BannerProduct
from products.database.discount_products import Discounts_product
from products.database.damage_products import DamageProducts, AddDamageProduct