# Generated by Django 4.0.4 on 2022-06-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('grant_type', models.CharField(max_length=100)),
            ],
        ),
    ]
