# Generated by Django 4.0.5 on 2022-08-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='maximum_user',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Maximum Users'),
        ),
    ]
