# Generated by Django 4.0.5 on 2022-07-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_deliverry',
            new_name='fast_delivery',
        ),
    ]
