# Generated by Django 4.0.5 on 2022-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded'), ('Failed', 'Failed'), ('Deleted', 'Deleted')], default='Pending', max_length=100),
        ),
    ]
