# Generated by Django 3.2.7 on 2022-06-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productreview_product_and_more'),
        ('accounts', '0017_billingaddress'),
        ('orders', '0002_alter_coupon_coupon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('is_order', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Customer Name')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products', verbose_name='Products')),
            ],
            options={
                'verbose_name_plural': 'Order Item',
            },
        ),
    ]
