# Generated by Django 4.0.5 on 2022-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_first_deliverry_order_fast_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On Hold', 'On Hold'), ('Refunded', 'Refunded'), ('Pending', 'Pending'), ('Order Failed', 'Order Failed'), ('Delete', 'Delete'), ('Order Confirmed', 'Order Confirmed'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order Processing', max_length=100),
        ),
    ]
