# Generated by Django 4.0.5 on 2022-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_banner_options_alter_bannerproduct_options_and_more'),
        ('orders', '0002_remove_coupon_minimum_user_coupon_maximum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='brand',
            field=models.ManyToManyField(blank=True, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.categories'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.products'),
        ),
    ]
