# Generated by Django 4.0.5 on 2022-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_feature_product'),
        ('orders', '0003_coupon_brand_coupon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='brand',
        ),
        migrations.AddField(
            model_name='coupon',
            name='brand',
            field=models.ManyToManyField(to='products.brand'),
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ManyToManyField(to='products.categories'),
        ),
    ]
