# Generated by Django 3.2.7 on 2022-06-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productreview_product_and_more'),
        ('accounts', '0017_billingaddress'),
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='accounts.profile', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='products.products', verbose_name='Products'),
        ),
    ]
