# Generated by Django 3.2.6 on 2022-06-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220629_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount_item',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
