# Generated by Django 4.0.5 on 2022-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_coupon_brand_alter_coupon_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
