# Generated by Django 3.2.6 on 2022-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_amount_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('SSL Commerz', 'SSL Commerz')], default='Cash on Delivery', max_length=100),
        ),
    ]
