# Generated by Django 4.0.5 on 2022-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_feature_product'),
        ('orders', '0004_remove_coupon_brand_coupon_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ManyToManyField(to='products.products'),
        ),
    ]
