# Generated by Django 3.2.7 on 2022-07-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_amount_item',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total Unit Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount_item',
            field=models.PositiveIntegerField(null=True, verbose_name='Unit Price'),
        ),
    ]
