# Generated by Django 4.0.5 on 2022-07-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_email_order_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_deliverry',
            field=models.BooleanField(default=False),
        ),
    ]
