# Generated by Django 4.0.5 on 2022-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fast_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Dhaka Fast Delivery', 'Dhaka Fast Delivery'), ('Dhaka Slow Delivery', 'Dhaka Slow Delivery'), ('Cash On Delivery', 'Cash On Delivery'), ('Sundarban', 'Sundarban')], default='Cash On Delivery', max_length=255),
        ),
    ]
