# Generated by Django 4.0.5 on 2022-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_fast_delivery_order_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fast_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
