# Generated by Django 3.2.7 on 2022-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
