# Generated by Django 4.0.4 on 2022-06-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='short_descriptions',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Short DesColorVariationcription'),
        ),
    ]
