# Generated by Django 3.2.7 on 2022-07-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_in_flash_sale',
        ),
    ]
