# Generated by Django 4.0.5 on 2022-08-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='bannerproduct',
            options={'verbose_name_plural': 'Banner Products Add'},
        ),
        migrations.RemoveField(
            model_name='bannerproduct',
            name='feature_product',
        ),
        migrations.AddField(
            model_name='banner',
            name='products',
            field=models.ManyToManyField(related_name='banner_products', through='products.BannerProduct', to='products.products'),
        ),
        migrations.AddField(
            model_name='bannerproduct',
            name='banner_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_product', to='products.products', verbose_name='Select Product'),
        ),
    ]
