# Generated by Django 4.0.5 on 2022-08-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_banner_options_alter_bannerproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Flash Discount Percantage')),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_product', to='products.products')),
            ],
            options={
                'verbose_name_plural': 'Discount Products Add',
            },
        ),
    ]
