# Generated by Django 4.0.4 on 2022-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_short_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariation',
            name='color_name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Color Name'),
        ),
        migrations.AlterField(
            model_name='sizevariation',
            name='size_name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Size Name'),
        ),
        migrations.AlterField(
            model_name='weightvariation',
            name='weight_name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Weight Name'),
        ),
    ]
