# Generated by Django 4.0.5 on 2022-08-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_name_supplier_supplier_name_and_more'),
        ('products', '0003_discounts_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_persoon', models.CharField(blank=True, max_length=100, null=True)),
                ('loss_amount', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('total_loss', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.outlet')),
                ('product', models.ManyToManyField(related_name='damege_product', to='products.products', verbose_name='product')),
            ],
            options={
                'verbose_name_plural': 'Damage Products List',
            },
        ),
    ]
