# Generated by Django 4.0.5 on 2022-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_regular_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
    ]
