# Generated by Django 4.0.4 on 2022-06-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_sku'),
        ('products', '0003_alter_colorvariation_color_name_and_more'),
    ]

    operations = [
    ]
