# Generated by Django 3.2.7 on 2022-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_website',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
