# Generated by Django 4.0.5 on 2022-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_quantity_products_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
