# Generated by Django 4.0.5 on 2022-07-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_stock_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('feature_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product', to='products.products')),
            ],
            options={
                'verbose_name_plural': 'Feature Products',
            },
        ),
    ]
