# Generated by Django 4.0.5 on 2022-08-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_name_supplier_supplier_name_and_more'),
        ('accounts', '0001_initial'),
        ('products', '0004_damage_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDamageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('quantity', models.IntegerField(null=True, verbose_name='quantity')),
                ('loss_per_unit', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_product', to='products.products', verbose_name='Damage Product')),
            ],
            options={
                'verbose_name_plural': 'Add Damage Product',
            },
        ),
        migrations.CreateModel(
            name='DamageProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('total_loss', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.outlet')),
                ('products_ids', models.ManyToManyField(related_name='damage_product_list', to='products.adddamageproduct')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
            options={
                'verbose_name_plural': 'Damage Products List',
            },
        ),
        migrations.DeleteModel(
            name='Damage_products',
        ),
    ]
