# Generated by Django 3.2.7 on 2022-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_in_flash_sale',
            field=models.BooleanField(default=False, verbose_name='Is this Product in Flash Sale'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
