# Generated by Django 4.0.4 on 2022-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_brand_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countreies',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_categories',
            name='sub_category_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
