# Generated by Django 4.0.5 on 2022-08-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_adddamageproduct_damageproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
