# Generated by Django 4.0.5 on 2022-07-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_feature_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('banner_image', models.ImageField(upload_to='product_filter_image')),
            ],
            options={
                'verbose_name_plural': 'Product By Query',
            },
        ),
        migrations.AddField(
            model_name='feature_product',
            name='product_by_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_query_select', to='products.product_filter'),
        ),
    ]
