# Generated by Django 4.0.5 on 2022-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
