# Generated by Django 4.0.4 on 2022-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, upload_to='slider_images'),
        ),
    ]
