# Generated by Django 4.0.5 on 2022-07-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_filter_feature_product_product_by_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name_plural': 'Feature Products',
            },
        ),
        migrations.RenameModel(
            old_name='Product_filter',
            new_name='Banner',
        ),
        migrations.DeleteModel(
            name='Feature_product',
        ),
        migrations.AddField(
            model_name='bannerproduct',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='products.banner'),
        ),
        migrations.AddField(
            model_name='bannerproduct',
            name='feature_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product', to='products.products'),
        ),
    ]
