# Generated by Django 4.0.5 on 2022-08-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_banner_is_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='Sub_category_products', to='products.sub_categories'),
        ),
    ]
