# Generated by Django 3.2.6 on 2022-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_slider_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='status',
        ),
        migrations.AddField(
            model_name='slider',
            name='url_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Slider URL Link'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
