# Generated by Django 4.0.4 on 2022-06-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220611_0111'),
        ('products', '0008_auto_20220610_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='accounts.profile', verbose_name='Profile Name'),
        ),
    ]
