# Generated by Django 3.2.6 on 2022-06-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_colorvariation_sizevariation_weightvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='products',
            name='upc',
        ),
        migrations.CreateModel(
            name='Variation_with_Price_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('regular_price', models.PositiveIntegerField(blank=True, null=True)),
                ('selling_price', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colorvariation', verbose_name='Product Color')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='products.products', verbose_name='Product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sizevariation', verbose_name='Product Size')),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.weightvariation', verbose_name='Product Weight')),
            ],
            options={
                'verbose_name_plural': 'Product Variation',
            },
        ),
    ]
