# Generated by Django 3.2.6 on 2022-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220618_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='regular_price',
        ),
        migrations.AlterField(
            model_name='variation_with_price_variant',
            name='regular_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variation_with_price_variant',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
