# Generated by Django 4.0.4 on 2022-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_expire_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
